In [1]:
import pandas as pd


df_pdh_data = pd.read_parquet("../data/PFAS_pdh_data.parquet")

In [ ]:
df_pdh_data.head()

,category,lat,lon,name,city,country,type,sector,source_type,data_collection_method,source_text,source_url,dataset_id,dataset_name,pfas_values,unit,pfas_sum,details,matrix,date,year
0,Known PFAS user,45.864286,5.948318,Fortier Beaulieu,Rumilly,France,Industrial site,NaN,Authorities,OSINT,ARS Rhône-Alpes,https://www.auvergne-rhone-alpes.ars.sante.fr/...,0,Known PFAS Users,[],NaN,NaN,{},NaN,NaN,NaN
1,Known PFAS user,45.838896,5.960591,Salomon,Rumilly,France,Industrial site,NaN,Authorities,OSINT,ARS Rhône-Alpes,https://www.auvergne-rhone-alpes.ars.sante.fr/...,0,Known PFAS Users,[],NaN,NaN,{},NaN,NaN,NaN
2,Known PFAS user,46.566759,4.904980,Tefal,Tournus,France,Industrial site,NaN,Authorities,OSINT,Géorisques,https://www.georisques.gouv.fr/risques/registr...,0,Known PFAS Users,[],NaN,NaN,{},NaN,NaN,NaN
3,Known PFAS user,47.984030,14.272978,Agru,Waldneukirchen,Austria,Industrial site,Manufacture of rubber and plastic products,Company,OSINT,Agru,https://www.agru.at/en/,0,Known PFAS Users,[],NaN,NaN,"{""maps_link"": ""https://goo.gl/maps/cSD9QcvjzUh...",NaN,NaN,NaN
4,Known PFAS user,48.032000,14.225225,Agru,Bad Hall,Austria,Industrial site,Manufacture of rubber and plastic products,Company,OSINT,Agru,https://www.agru.at/en/,0,Known PFAS Users,[],NaN,NaN,"{""maps_link"": ""https://goo.gl/maps/NkuHEHiEQbV...",NaN,NaN,NaN

In [4]:
df.columns

Index(['category', 'lat', 'lon', 'name', 'city', 'country', 'type', 'sector',
       'source_type', 'data_collection_method', 'source_text', 'source_url',
       'dataset_id', 'dataset_name', 'pfas_values', 'unit', 'pfas_sum',
       'details', 'matrix', 'date', 'year'],
      dtype='str')

In [ ]:
df["pfas_values"]

In [3]:
df.describe()

                 lat            lon    dataset_id      pfas_sum          year
count  962578.000000  962578.000000  1.318803e+06  1.306161e+06  1.306161e+06
mean       47.124828       3.385397  6.615665e+01  1.201510e+04  2.019730e+03
std         6.652142       7.655517  4.646898e+01  1.439395e+06  3.860241e+00
min       -21.382742     -63.079635  0.000000e+00  0.000000e+00  1.977000e+03
25%        45.484994       0.619755  2.800000e+01  0.000000e+00  2.017000e+03
50%        47.862265       3.433731  2.900000e+01  0.000000e+00  2.020000e+03
75%        49.347885       5.419144  1.240000e+02  3.000000e+00  2.023000e+03
max        84.050500     121.608000  1.430000e+02  8.002451e+08  2.026000e+03

# ICPE

In [5]:
import pandas as pd


df_icpe = pd.read_parquet("../data/pdh_icpe_export.parquet")

In [6]:
df_icpe.columns

Index(['category', 'lat', 'lon', 'name', 'city', 'country', 'type', 'sector',
       'source_type', 'data_collection_method', 'source_text', 'source_url',
       'dataset_id', 'dataset_name', 'pfas_values', 'unit', 'pfas_sum',
       'details', 'matrix', 'date', 'year'],
      dtype='str')

In [9]:
df_pdh_data.columns

Index(['category', 'lat', 'lon', 'name', 'city', 'country', 'type', 'sector',
       'source_type', 'data_collection_method', 'source_text', 'source_url',
       'dataset_id', 'dataset_name', 'pfas_values', 'unit', 'pfas_sum',
       'details', 'matrix', 'date', 'year'],
      dtype='str')

In [6]:
pd.get_option("display.max_columns")

20

In [19]:
pd.set_option("display.max_columns", None)

df_icpe.head()

,category,lat,lon,name,city,country,type,sector,source_type,data_collection_method,source_text,source_url,dataset_id,dataset_name,pfas_values,unit,pfas_sum,details,matrix,date,year
0,Measurement,41.041963,-0.556805,PHYTEUROP INDUSTRY - REJETS STEP PRESLES (Aval),MONTREUIL-BELLAY,France,Sampling location,NaN,Authorities,Public data - Download,DREAL Pays de la Loire,https://www.pays-de-la-loire.developpement-dur...,142,France - ICPE,"[{""cas_id"":""375-22-4"",""unit"":""ng/l"",""substance...",ng/l,2500.0,"{""url_fiche"":""https://www.georisques.gouv.fr/r...",Wastewater,2026-02-11,2026
1,Measurement,41.041963,-0.556805,PHYTEUROP INDUSTRY - REJETS STEP PRESLES (Aval),MONTREUIL-BELLAY,France,Sampling location,NaN,Authorities,Public data - Download,DREAL Pays de la Loire,https://www.pays-de-la-loire.developpement-dur...,142,France - ICPE,"[{""cas_id"":""375-95-1"",""unit"":""ng/l"",""substance...",ng/l,2500.0,"{""url_fiche"":""https://www.georisques.gouv.fr/r...",Wastewater,2026-01-22,2026
2,Measurement,41.041963,-0.556805,PHYTEUROP INDUSTRY - REJETS STEP PRESLES (Aval),MONTREUIL-BELLAY,France,Sampling location,NaN,Authorities,Public data - Download,DREAL Pays de la Loire,https://www.pays-de-la-loire.developpement-dur...,142,France - ICPE,"[{""cas_id"":""2706-91-4"",""unit"":""ng/l"",""substanc...",ng/l,2500.0,"{""url_fiche"":""https://www.georisques.gouv.fr/r...",Wastewater,2025-12-22,2025
3,Measurement,41.671522,8.906249,SARL LANFRANCHI ENVIRONNEMENT - Bassin eaux pl...,VIGGIANELLO,France,Sampling location,NaN,Authorities,Public data - Download,DREAL Corse,https://www.corse.developpement-durable.gouv.f...,142,France - ICPE,"[{""cas_id"":""335-67-1"",""unit"":""ng/l"",""substance...",ng/l,12.0,"{""url_fiche"":""https://www.georisques.gouv.fr/r...",Surface water,2024-04-04,2024
4,Measurement,41.671522,8.906249,SARL LANFRANCHI ENVIRONNEMENT - Drain sous cas...,VIGGIANELLO,France,Sampling location,NaN,Authorities,Public data - Download,DREAL Corse,https://www.corse.developpement-durable.gouv.f...,142,France - ICPE,"[{""cas_id"":""335-67-1"",""unit"":""ng/l"",""substance...",ng/l,8.0,"{""url_fiche"":""https://www.georisques.gouv.fr/r...",Surface water,2024-04-04,2024

In [14]:
df_pdh_data.sector.unique()

<ArrowStringArray>
[                                                          nan,
                  'Manufacture of rubber and plastic products',
                    'Manufacture of plastics in primary forms',
                   'Manufacture of refined petroleum products',
                   'Treatment and disposal of hazardous waste',
                   'Manufacture of pulp, paper and paperboard',
       'Manufacture of other fabricated metal products n.e.c.',
               'Treatment and disposal of non-hazardous waste',
                             'Treatment and coating of metals',
                                                    'Sewerage',
             'Manufacture of articles of paper and paperboard',
                'Manufacture of other organic basic chemicals',
                                       'Finishing of textiles',
 'Tanning and dressing of leather; dressing and dyeing of fur']
Length: 14, dtype: str

In [16]:
df_pdh_data["sector"].value_counts(dropna=False)

sector
NaN                                                            1312791
Sewerage                                                          1585
Manufacture of pulp, paper and paperboard                         1107
Treatment and disposal of non-hazardous waste                      891
Treatment and coating of metals                                    667
Manufacture of articles of paper and paperboard                    506
Treatment and disposal of hazardous waste                          387
Manufacture of plastics in primary forms                           223
Manufacture of refined petroleum products                          188
Manufacture of rubber and plastic products                         150
Manufacture of other fabricated metal products n.e.c.              127
Finishing of textiles                                              124
Manufacture of other organic basic chemicals                        46
Tanning and dressing of leather; dressing and dyeing of fur         11
Name: count, dtype: int64

In [13]:
list(df_pdh_data.name.unique())

['Fortier Beaulieu',
 'Salomon',
 'Tefal',
 'Agru',
 'Freudenberg',
 'Technofyon',
 'ANSUL',
 'Chemours',
 'MCM',
 'Orchidee',
 'Shamrock Technologies',
 'Synthomer',
 'UNITEQ',
 'Vaneflon',
 'Wevapress Thermoplastics',
 'Xtraflex',
 'Huntsman',
 'Serto',
 'Wacker Chemie ',
 'Linatex',
 'O.L. Seals',
 'Fluorplast',
 'PRP-Plastic',
 '3P Performance Plastics Products',
 'Aberflon',
 'BASF Agri Solutions',
 'BioEx',
 'C2M Aurochs Industrie',
 'DEMGY SPN ',
 'Eau et Feu',
 'Fluor one',
 'Fluorotechnique',
 'IKV Tribology',
 'Maceplast',
 'Perimeter Solutions / Biogema',
 'Pirep',
 'SAFI',
 'Sectoriel',
 'Spirel',
 'Techniflon Europe',
 'Tricoflex',
 'Weilburger coatings',
 '3P - Performance Plastics Products',
 'AFD Advanced Fluoropolymer Devices',
 'BASF',
 'Baum',
 'Bernd Schwegmann',
 'Byk',
 'Central Glass Germany',
 'CHT Bezema',
 'Ensinger',
 'Fiberflon',
 'Fluor-tech Kunststoffe',
 'Freudenberg Sealing Technologies',
 'Herzogenaurach',
 'Kapp Chemie ',
 'Klüber',
 'Lefatex Chemie ',
 'Momentive',
 'PTFE Competence Center',
 'PTFE Nünchritz',
 'PTFE Solutions',
 'PTFE-Europe',
 'PTFE-Solutec',
 'ptfe24',
 'Rudolf Chemie',
 'Rudolf Gutbrod Kunststoffbeschichtungen',
 'Rühl ',
 'Schill+Seilacher',
 'Solvay',
 'Spengler Fluorkunststoffe',
 'STHAMER',
 'Synthetica Fluorplastics',
 'TEKU Fluorkunststoffe',
 'Thor',
 'Trans-Textil',
 'Vector Foiltec',
 'Wacker Chemie',
 'Saint-Gobain',
 '3P Produits Plastiques Performants',
 'Ammeraal Beltech',
 'FELIS Srl Unipersonal',
 'Guarniflon',
 'ITAflon',
 'L.M.P. Fluorcarbon',
 'Maflon',
 'Near Chimica',
 'ProFoam',
 'Rhütten',
 'Ricci',
 'SABO Foam',
 'Teknofluor',
 '3M',
 'Daikin Chemical ',
 'Fluortech',
 'Polycomp',
 'Polyfluor Plastics',
 'Ridderflex & Plastics',
 'Sun Chemical',
 'Tanatex',
 'Nordic Fire ',
 'EDER',
 'Plastics constructions',
 'Fluorocarbons',
 'Dastaflon',
 '3P Productos Plásticos Performantes',
 'Perimeter Solutions Auxquimica',
 'Sabo Española',
 'SAFI FÁBRICA DE VÁLVULAS',
 'Trumpler',
 'VS Focum',
 'Fomtec',
 'Metaflon',
 '3F',
 'Aflex Hose',
 'AFT Fluorotec',
 'Angus Fire',
 'Apollo Scientific',
 'Beldam Crossley',
 'Duraflon',
 'Elekem',
 'Fothergill Group',
 'Grange Tubes',
 'Green Tweed',
 'Holscot Fluoropolymers',
 'M&I Materials ',
 'Oiltechnic ',
 'PTFE Applied Coatings',
 'PTFE Coatings',
 'PTFE Developments',
 'PTFEFLEX',
 'Techbelt',
 'Tyco',
 'Victrex',
 'Victrex ',
 'Victrex Seal Sands',
 'Whitfield',
 'Merck KGaA',
 'W. L. Gore',
 'nan',
 'Merck',
 'Lenzing Plastics',
 'Gunnar Haagensen',
 'Approflon',
 'BAYERNOIL Raffinerie',
 'Exolum Mannheim GmbH',
 'Gunvor Raffinerie Ingolstadt',
 'HES Tank Terminal GmbH/HES Wilhelmshaven Tank Terminal GmbH',
 'Magdeburger Umschlag und Tanklager Dettmer GmbH',
 'Covestro',
 'Alfa',
 'Binox',
 'Caast',
 'Cavagna',
 'CDR',
 'Diflon',
 'Esa',
 'FHT',
 'FIP/Aliaxis',
 'Fluorseals',
 'Fluorten',
 'Iris Green',
 'Isoflon',
 'IVR',
 'Robecchi',
 'Stegi',
 'Valvole',
 'Exolum Amsterdam',
 'Neste',
 'Unified Fire Brigade (Gezamenlijke Brandweer)',
 'mcp engineering plastics',
 'TREDI',
 'EXXONMOBIL PETROLEUM & CHEMICAL - ESSO RAFFINADERIJ',
 'Smurfit Kappa Kraftliner Piteå',
 'Stora Enso Oyj, Imatran tehtaat',
 'ARKEMA FRANCE',
 '"Olovno-tsinkov kompleks" AD',
 "Steven's Croft Power Station",
 'AB "ORLEN Lietuva"',
 'Neste Oyj, Porvoon jalostamo',
 'HELIO PRINT',
 'VALBOM',
 'Stadt Regensburg - Klärwerk',
 'Hammerfest LNG',
 'Aurubis AG',
 'ORION ENGENEERED CARBONS SAS',
 'MHB Betriebsführungsgesellschaft mbH',
 'UNIÓN DE EMPRESAS MADERERAS, SAU',
 'Speira GmbH',
 'TOTALENERGIES RAFFINAGE FRANCE',
 'V.N.AUTOMÓVEIS, S.A',
 'TOTALENERGIES MARKETING SERVICES',
 'Westlake Vinnolit GmbH & Co. KG, Werk Burghausen',
 'Gunvor Energy Rotterdam B.V. (GPR)',
 'Energie AG Oberösterreich Umwelt Service GmbH',
 'Henkel Ireland Operations and Research Limited  (Ballyfermot)',
 'Stora Enso De Hoop B.V.',
 'EEW Energy from Waste Heringen GmbH',
 'Stena Recycling Sp. z o.o. oddział we Wschowie',
 'Lidköpings Värmeverk, Filen',
 'UMICORE - HOBOKEN',
 'Termovalorizzatore di Scarlino',
 'Repo Vabrikud AS, Püssi puitlaastplaaditehas',
 'LINEX PANNEAUX',
 'SLOVNAFT, a.s.',
 'MAL Zrt. "f.a."',
 'UPM-Kymmene Oyj, Kaukaan tehtaat',
 'Esso Norge, Slagentangen',
 'Stora Enso Oyj, Sunilan tehdas',
 'Biomassekraftwerk Lünen GmbH',
 'Shell Nederland Raffinaderij BV',
 'GALVANOTECNICA & PM SRL IN LIQUIDAZIONE',
 'I/S AffaldPlus, Slagelse Affaldsenergi',
 'ALUMINIO ESPAÑOL, SA',
 'SEMARIV',
 'Polski Koncern Naftowy ORLEN S.A.',
 'Södra Cell Mörrum',
 'VISCOFAN ESPAÑA S.L.U.',
 'SUEZ RV ENERGIE',
 'HVC N.V.',
 'WRG - Wilhelmshavener Raffinerie- gesellschaft mbH',
 'SC EGGER ROMANIA SRL Radauti',
 'Tampereen Vesi Oy, Viinikanlahden jätevedenpuhdistamo',
 'CIRES (CI)',
 'Sonae Industria (UK) Limited',
 'ProRheno AG',
 'REPSOL QUÍMICA S.A.',
 'MM Frohnleiten GmbH',
 'Viridor Waste (Somerset) Ltd, Dimmer Landfill Site',
 'Rekular GmbH ',
 'LEIPA Georg Leinfelder Werk Schwedt Nord ',
 'Fjernvarme Horsens A/S, Horsens Kraftvarmeværk',
 'Klärwerk München I Gut Großlappen',
 'Alstom Grid Products/GIS/BHT-FSA',
 'Raffineria ISAB Impianti SUD',
 'swb Entsorgung GmbH & Co. KG',
 "COMPAGNIE DES EAUX ET DE L'OZONE PROCEDES M P OTTO",
 'UPM GmbH, Werk Augsburg',
 'versalis stabilimento di Sarroch',
 'Faxe Kalks Modtageplads for affald fra ovnanlægget',
 'Munksjö Paper AB Billingsfors',
 'Etablissement des Flandres',
 'Städtische Werke, Kraftwerk Kassel',
 'KEM ONE',
 'STORA ENSO LANGERBRUGGE',
 'Sapa Aluminium Sp. z o.o.',
 'Niersverband, Kläranlage Goch',
 'Westfield Biomass Plant',
 'Technocell Dekor GmbH & Co. KG',
 'Petroplus Raffinage Reichstett',
 'Sita Uk Limited, Ellington Road Landfill Site',
 'OMV PETROM SA - Petrobrazi',
 'VIPAP VIDEM KRŠKO',
 'KEZO Hinwil',
 'Model Sachsen Papier GmbH ',
 'Nordværk I/S - Energianlægget Hjørring',
 'Petrogal-Refinaria do Porto (CI)',
 'FERROGLOBE FRANCE',
 'Egger Holzwerkstoffe Markt Bibart GmbH',
 'SAICA PAPER EL BURGO DE EBRO',
 'KEYSER et FILS',
 'Waggeryd Cell AB',
 'AIRBUS ATLANTIC',
 'FÁBRICA DE MENGÍBAR (SMURFIT KAPPA ESPAÑA, S.A.)',
 'Shotton Paper Mill',
 'AALBERTS SURFACE TECHNOLOGIES SAS',
 'Navigator Figueira (CI)',
 'Celulose Beira Industrial (Celbi), S.A. (CI)',
 'Hammel Fjernvarme A M B A',
 'SARP INDUSTRIES',
 'Metsä Fibre Oy, Joutsenon tehdas',
 'DIJON METROPOLE',
 'AustroCel Hallein GmbH',
 'SYLVAMO FRANCE SA',
 'Elkem Rana AS',
 'STEICO Sp. z o.o. Zakład w Czarnkowie',
 'Inovyn Sverige AB',
 'Aurubis Olen',
 'DISLAUB',
 'GfA Lüneburg - gkAöR Vorstand Oliver Schmitz',
 'SELCHP Energy Recovery Facility',
 'Kronospan Energy s.a.',
 'SAFT',
 'Stadtwerke Düsseldorf AG',
 'Nynas Plant',
 'Stoke EfW Facility',
 'Unidade da Meia Serra (A, EVE, TM, VO, S) (CI)',
 'Morayhill Timber Mill',
 'GALLI ',
 'ARN B.V.',
 'FINANCIERA MADERERA, S.A. - RÁBADE E BEGONTE',
 'AVAG KVA AG',
 "TIBI sc - Usine d'incinération",
 'EVERE',
 'SIMOREP ET CIE',
 'Shell North Sea Gas Terminal',
 'MIRO-Mineralölraffinerie Oberrhein GmbH & Co.KG Werk 1',
 'Mondi Powerflute Oy, Puunjalostusteollisuus, Mondi Powerflute Oy',
 'INEOS STYROLUTION FRANCE SAS',
 'KVA Winterthur',
 'UPM-Kymmene Oyj, Kymi',
 'Hagener Umweltservice- und Investitionsgesellschaft mbH (HUI GmbH)',
 'EGK Entsorgungsgesellschaft Krefeld GmbH & Co. KG',
 'SICTOM ENTRE MONTS ET VALLÉES',
 'Crealis Nederland BV',
 'ALU IBÉRICA LC, SL - LA CORUÑA',
 'Müllverbrennung Kiel GmbH & Co. KG - Müllheizkraftwerk Kiel ',
 'JAI Overfladebehandling A/S',
 'PEUGEOT CITROEN RENNES SNC',
 'Stadtentwässerung und Umweltanalytik Nürnberg, Klärwerk 1',
 'Abfallheizkraftwerk Geiselbullach',
 'Teesside EfW Plant EPR/VP3034SG',
 'Technologie',
 'NAVIGATOR Setúbal (CI)',
 'DAMCO Aluminium Delfzijl Coöperatie U.A.',
 'SC ALRO SA SLATINA - Sediu primar',
 'AVR-Afvalverwerking',
 'UIOM de La Roseraie',
 'PRATT WHITNEY RZESZÓW SPÓŁKA AKCYJNA',
 'Bio-El, Fredrikstad',
 'FERROGLOBE SPAIN METALS, S.A.U.',
 'SIA “KRONOSPAN Riga"',
 'Mercer Stendal GmbH ',
 'MVA Weisweiler GmbH & Co. KG',
 'FLUXEL',
 'COGAL BELGIUM',
 'SC KASTAMONU ROMANIA SA',
 'Fritz Egger GmbH & Co. OG',
 'ETAR de Setúbal (CI)',
 'Landeshauptstadt Klagenfurt',
 'EDAR GUADALETE',
 'RWZI Bath',
 'Gruppenklärwerk Memmingen',
 'East Worthing STW',
 'CU LIMOGES METROPOLE',
 'Abwasserverb.Untere Ahr ',
 'RWZI Nieuwegein',
 'Kläranlage Dortmund-Deusen, Emschergenossenschaft',
 'ETAR Companheira (CI)',
 'IMPIANTO DEPURAZIONE DI MERONE',
 'Orb Electrical Steels',
 'Emschergenossenschaft, Kläranlage Duisburg-Alte Emscher',
 'FIVE FORDS STW',
 'AQUANET Spółka Akcyjna Lewobrzeżna Oczyszczalnia Ścieków',
 'OXFORD STW',
 'ACQUE VERONESI S.C.AR.L. - DEPURATORE DI VANGADIZZA',
 'EDAR RANILLA',
 'ETAR Alcântara (CI)',
 'EPURIA',
 'Cabot Lane Waste Water Treatment Works',
 'IMPIANTO DI DEPURAZIONE VALLE DELLAGNO',
 'Caister Stw F/E - Caister',
 'Cork City',
 'STE BEARNAISE DE GESTION INDUSTRIELLE',
 'ALFA S.R.L.',
 'Davyhulme Atf Plant',
 'Coleshill STW',
 'MIEJSKO-PRZEMYSŁOWA OCZYSZCZALNIA ŚCIEKÓW SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ',
 'EDAR BLANES',
 'SC AQUAVAS SA - SUCURSALA VASLUI',
 'DuPont Nutrition & Health (tidligere FMC)',
 'STATIA DE EPURARE APE UZATE SIBIU',
 'Abwasserreinigungsanlage / Röti',
 'SLOUGH STW',
 'Turun seudun puhdistamo Oy, Kakolanmäen jätevedenpuhdistamo',
 'RWZI Rijen',
 'SYND INTERCOM ASSAINISSEMENT MARNE LA VALLEE',
 'Ray Hall Sand Filters STW',
 'Stockport Stw',
 'Cambridge STW',
 'Impianto di depurazione di Fusina',
 'DEPURATORE GENNA',
 'Bedford STW',
 'RWZI Hellevoetsluis',
 'AWZI Tollebeek',
 'ETAR Coimbrão (Norte) (CI)',
 'AFAN WWTW',
 'IMPIANTO DEPURATIVO DI FOGGIA',
 'OULUN VESI, Taskilan jätevedenpuhdistamo, Oulu',
 'Lancaster Stw',
 'Nordwasser GmbH  ',
 'Gruvöns bruk',
 'Waste water treatment plant - Varna',
 'Partington Paper Mill EPR/ZP3736XH',
 'FAENZA DEPURAZIONI S.R.L.',
 'CONSORZIO CUOIODEPUR SPA',
 'Rioolwaterzuiveringsinstallatie Hengelo',
 'Uppsala Avloppsreningsverk',
 'SKA Balingen des ZVA Balingen ',
 'Hauptklärwerk Mühlhausen ',
 'Egsmade Renseanlæg (renseanlæg)',
 'Waste water treatment plant - Dobrich',
 'ACQUE VERONESI S.C.A R. L. - DEPURATORE DI VANGADIZZA',
 'Burnley Stw',
 'Kanalizacioni sistem grada Novog Sada',
 'Impianto di depurazione di LEVICO TERME',
 'Shieldhall Sewage Treatment Works',
 'LINEG, Kläranlage Moers-Gerdt',
 'Worcester STW',
 'Zakład Wodociągów i Kanalizacji /oczyszczalnia ścieków/',
 'Javno podjetje Centralna čistilna naprava Domžale-Kamnik',
 'SC RAJA SA - SE CONSTANTA SUD',
 'ETAR de Vilamoura (CI)',
 'ESTACIÓN DEPURADORA DE AGUAS RESIDUALES DE VALLADOLID',
 'Kidderminster STW',
 'EDAR VILA-SECA I SALOU',
 'METROPOLE EUROPEENNE DE LILLE',
 'Kläranlage Lippstadt Stadtentwässerung Lippstadt AöR',
 'Stadt Bergisch Gladbach',
 'TBZ - Kläranlage Kielseng  ',
 'DEPURATORE ACQUE REFLUE URBANE DI VERCELLI',
 'Raffineria di Milazzo S.C.p.A.',
 'Blackburn Stw',
 'RWZI Deurne',
 'Hartshill STW',
 'RWZI Asten (Waterschap Aa en Maas)',
 'Klärwerk Kulmbach',
 'Nigg Sewage Treatment Works',
 "SOCIETE D'ASSAINISSEMENT ET DE GESTION DE L'ENVIRONNEMENT DU BASSIN D'ARCACHON",
 'ViK Uređaj Stupe',
 'E.P.A.R. EL PISÓN',
 'GVRZ Kläranlage Schönau',
 'Davyhulme Stw',
 'St Helens Stw',
 'STEP - TOUGAS',
 'WASSERVBD REGION GRATKORN-GRATWEIN',
 'Abwasserzweckverband, Untere Selz ',
 'EDAR SITGES-SANT PERE DE RIBES',
 'SKA Donaueschingen GVV Donaueschingen',
 'DEPURATORE DI SERVOLA',
 'KÄPPALAVERKET',
 'COMMUNAUTE AGGLOMERAT FREJUS ST RAPHAEL',
 'DEPURATORE ACQUE REFLUE URBANE DI CREMA - SERIO 1',
 'SKA AHW WIESLOCH ',
 'SKA AZV UNTERE HARDT St.Ilgen',
 'EDAR IGUALADA',
 'Wupperverband, Kläranlage Solingen-Burg',
 'SI GROUP- BETHUNE',
 'BRADFORD ESHOLT STW',
 '"WODOCIĄGI SŁUPSK" SPÓŁKA Z O. O.',
 'JP VOKA SNAGA, Centralna čistilna naprava Ljubljana',
 'DEPURATORE CITTA DI CASTELLO',
 'Portobello STW (Brighton)',
 'Fejérvíz ZRt.',
 'VIO-HRUŠČICA',
 'Impianto di depurazione centralizzato di Collegno',
 'SMURFIT NAVARRA, S.A.-SANGÜESA',
 'AZV Ermstal, Metzingen',
 'Depuratore di Bolzano',
 'Impianto di depurazione di TRENTO NORD',
 'Miejska Oczyszczalnia Ścieków',
 'STEP - LESCAR',
 'Impianto di depurazione centralizzato di Castiglione Torinese',
 'EDAR ANTILLA',
 'Klärwerk Gießen',
 'Dundalk',
 'Kläranlage Neumünster  ',
 'Podružnica Knin',
 'Impianto depurazione acque reflue di Brembate',
 'UAB "Kauno vandenys"',
 'GESM S.p.A. Fashion Factory',
 'EYDAP S.A. - PSYTTALIA WASTEWATER TREATMENT PLANT',
 'EDAR EL EJIDO',
 'Lynetten (renseanlæg)',
 'Holdenhurst STW',
 'Abwasser, Grün & Lüneburger Service GmbH',
 'Kläranlage Menden, Ruhrverband',
 'ARA Rhein AG',
 'IMPIANTO DI SESTO SAN GIOVANNI',
 'E. Miroglio EAD',
 'Kläranlage Celle mit BHKW',
 'ESTACIÓN DEPURADORA DE AGUAS RESIDUALES DE PALENCIA',
 'Eastleigh STW',
 'Reinhaltungsverband Steyr und Umgebung',
 'STATIA DE EPURARE APE UZATE ROMAN',
 'Kläranlage Fürth',
 'PAPETERIE LE BOURRAY',
 'Reinhalteverband Großraum Salzburg',
 'Sjölunda Avloppsreningsverk',
 'Mivíz Miskolci Vízmű Kft.',
 'Miejskie Przedsiębiorstwo Wodociągów i Kanalizacji S.A., Oczyszczalnia ścieków "Pola Irygowane Osobowice" ',
 'CALDER VALE STW',
 'ZKA Chemnitz-Heinersdorf',
 'USINE DE DÉPOLLUTION DE ROMANS SUR ISÈRE',
 'MIRO-Mineralölraffinerie Oberrhein GmbH & Co.KG Werk 2',
 'Stadtentwässerung Frankfurt am Main - Sindlingen',
 'SC APAVITAL SA IASI-STATIA DE EPURARE IASI',
 'United Utilities Water Plc, Bromborough Stw',
 'Hull WwTW Combustion Plant',
 'Klärwerk Augsburg',
 'Sentralrenseanlegget for Nord Jæren SNJ',
 'Biocel Paskov a.s.',
 'Ruhrverband, Kläranlage Essen-Süd',
 'DEPURATORE ACQUE REFLUE DI FORLI',
 'SKA Konstanz ',
 'Kilkenny City Waste Water Treatment plant',
 'INOVYN ESPAÑA (FABRICACIÓ DE VCM I PVC - BA20110024)',
 'api Raffineria di Ancona spa',
 'Depuratore "SantAgostino"',
 'IMPIANTO DI DEPURAZIONE TOBEL',
 'Viva Servizi S.p.A.',
 'STEP - LE PETIT-QUEVILLY',
 'EDAR RIERA DE LA BISBAL',
 'IMPIANTO DI DEPURAZIONE DI MONSELICE',
 'IMPIANTO DI DEPURAZIONE ACQUE REFLUE DI COLOGNO AL SERIO',
 'UAB "AUKŠTAITIJOS VANDENYS" ',
 'Miejskie Przedsiębiorstwo Wodociagów i Kanalizacji S.A. Wrocławska Oczyszczalnia Ścieków Janówek',
 'Preston Wwtw',
 'RWZI Gent',
 'Grupowa Oczyszczalnia Ścieków Sp. z o.o',
 'Wodociągi Miejskie w Radomiu Spółka z o.o. Zakład Kanalizacyjny',
 'Centralna Oczyszczalnia Ścieków - COŚ',
 '"Miejskie Przedsiębiorstwo Wodociągów i Kanalizacji w Lublinie" Sp. z o.o., Oczyszczalnia ścieków "Hajdów"',
 'EDAR VIC',
 'Klärwerk Neumarkt i.d.OPf.',
 'Kläranlage Kamen- Körnebach, Lippeverband',
 'SKA BIETIGHEIM - BIETIGHEIM-BISSINGEN',
 'Águas de Barcelos - ETAR de Barcelos (CI)',
 'STATIA DE EPURARE ORADEA',
 'OCZYSZCZALNIA ŚCIEKÓW FORDON',
 'HUDDERSFIELD STW',
 'IMPIANTO DI DEPURAZIONE DI CERVIA',
 'VAN MOER CLEANING & REPAIR - KAAI 200',
 'Vcsm Zrt. Szolnok',
 'Wydział Oczyszczalni Ścieków',
 'Napapiirin Vesi Oy, Rovaniemen kaupungin jätevedenpuhdistamo',
 'RWZI Elburg',
 'EYATH S.A. – SINDOS WASTEWATER TREATMENT PLANT',
 'E.D.A.R. SOTOGUTIERREZ',
 'Impianto di depurazione Consortile Carini',
 'BLAIKENGRUVAN',
 'Kläranlage Mainz ',
 'QUALIPAC AURILLAC',
 'Komunalno podjetje Ptuj d.d., CČN Ptuj',
 'Lincoln(Canwick) STW',
 "Ta' Barkat South Sewage Treatment Plant",
 'Oczyszczalnia Ścieków w Białymstoku',
 'Bytomskie Przedsiębiorstwo Komunalne Sp. z o.o.',
 'Gemeindeabwasserverband Amstetten',
 'REGIE DES EAUX DE MONTPELLIER MEDITERRANEE METROPOLE',
 'Oczyszczalnia ścieków',
 'Grupowa Oczyszczalnia Ścieków',
 'SKA Mergelstetten, Heidenheim ',
 'COMPANIA DE APA SOMES SA CLUJ-NAPOCA - Statia de epurare ape uzate urbane',
 'EDAR MONTCADA I REIXAC',
 'Impianto di Termovalorizzazione Rifiuti di Trieste - via Errera 11',
 'Stadt Kiel Klärwerk Altbülk  ',
 'CONSORZIO PER LA DEPURAZIONE DELLE ACQUE DI SCARICO',
 'SKA AZV STAUFENER BUCHT-GREZHAUSEN Kläranlage Grezhausen',
 'Mercer Rosenthal GmbH ',
 'IDL Baciacavallo',
 'ESTACIÓN DE PRETRATAMIENTO  Y BOMBEO DE CABO LLANOS',
 'IMPIANTO DEPURAZIONE ACQUE REFLUE FERRARA',
 'ACQUE INDUSTRIALI SRL - IMPIANTO DI PONTEDERA',
 'Kläranlage Iserlohn-Baarbachtal, Ruhrverband',
 'Stadt Rheda-Wiedenbrück Abwasser KA (Rheda-Wiedenbrück, Rheda)',
 'SC AQUATIM SA- Sector epurare Timisoara',
 'WASTEWATER TREATMENT PLANT OF CHANIA',
 'Abwasserwerk Rosenbergsau',
 'Raubling Papier GmbH',
 'Essity Operations Mannheim GmbH ',
 'STEP - COLMAR',
 'Shanganagh-Bray',
 'AbwVbd an der Traisen',
 'Waste water treatment plant - Sliven',
 'IMPIANTO DI DEPURAZIONE ACQUE REFLUE URBANE',
 'PUBLIACQUA SPA-IDL PISTOIA CENTRALE PASSAVANT',
 'EWE WASSER GmbH Kläranlage Cuxhaven',
 'Oczyszczalnia Ścieków "WARTA" S.A.- Centralna Oczyszczalnia Ścieków',
 'Abwasserverband Obere Lutter',
 'RWZI Eindhoven (Waterschap De Dommel)',
 'RWZI DENDERMONDE',
 'Impianto di depurazione di Treviso - Via Cesare Pavese',
 'ZKA Konstanz',
 'Smedjeholms ARV (Falkenberg)',
 'Rochdale Stw',
 'Dunfermline Sewage Treatment Works',
 'Elkem Bremanger',
 'Culmore WWTWs',
 'CONSORZIO DEL TORRENTE PESCIA SPA',
 'EDAR 2-EMAYA,S.A.',
 'RWZI Aartselaar',
 'Cliff Quay Waste Water Treatment Works',
 'EDAR ARROYO DE LA MIEL',
 'DEPURATORE DI RICCIONE',
 'Thisted',
 'Abwasserreinigungsanlage REAL',
 'sito di Brindisi',
 'Komunalna Oczyszczalnia Ścieków',
 'BRIVADOISE DE TRAITEMENT DE SURFACES',
 'METROPOLE TOULON-PROVENCE-MEDITERRANEE',
 'SKA AZV UNTERES SULMTAL NECKARSULM',
 'Impianto di depurazione Fondo verde',
 'Publiacqua S.p. A. - sito San Colombano Case Passerini',
 'Boliden Harjavalta Oy, Porin kuparielektrolyysi',
 'DSP',
 'Kronopol Sp. z o.o.',
 'Smurfit Kappa Nettingsdorf AG & Co KG',
 'TERMOVALORIZZATORE CCS POZZILLI',
 'PCK Raffinerie GmbH Schwedt  ',
 'Zellstoff Pöls Aktiengesellschaft',
 'TRIADE ELECTRONIQUE',
 'Statkraft Markets GmbH (Biomasseheizkraftwerk)',
 'L & T Teollisuuspalvelut Oy, Munaistenmetsän jätteenkäsittelykeskus, Munaistenmetsän jätteenkäsittelykeskus, Uusikaupunki',
 'SA DE LA RAFFINERIE DES ANTILLES',
 'LARISSA WASTE WATER TREATMENT PLANT',
 'impianto di recupero/smaltimento rifiuti pericolosi e non pericolosi',
 'Dudley Energy from Waste Facility EPR/AP3435SD',
 'VERNEA',
 'MHKW Weißenhorn',
 'FunderMax GmbH',
 'ELKEM ASA AVD BJØLVEFOSSEN',
 'Vlisco Netherlands BV',
 'Slough Heat and Power',
 'AVG Abfallentsorgungs- und Verwertungsgesellschaft Köln mbH',
 'Vantaan Energia Oy, Jätevoimala',
 'EVO - MHKW Offenbach',
 'Scania Production Zwolle BV',
 'VM BUILDING SOLUTIONS',
 'TERMIZO a.s.',
 'EXXONMOBIL PETROLEUM & CHEMICAL BV - MEERHOUT POLYMERS PLANT',
 'PREZERO SERVICIOS URBANOS DE MURCIA, S.A.',
 'GREEN CAPITAL PARTNERS (FUNTAM)',
 'SOCIETE ORLEANAISE DE VALORISATION DES DECHETS',
 'Sonae Arauco Deutschland GmbH Werk Meppen',
 'BP WYTCH FARM GATHERING STATION AND WELLSITES',
 'Puhos Board Oy, Puhoksen lastulevytehdas',
 'OIE AG ',
 'Heinzel Steyrermühl Energie GmbH',
 "VALO'MARNE",
 'COMPAGNIE GENERALE D ENVIRONNEMENT DE CERGY PONTOISE',
 'LAZIO AMBIENTE S.P.A.',
 'SCA CULTURES FRANCE CHAMPIGNON - Centrale de LONGUE',
 'WIEN ENERGIE GmbH',
 'TERMOVALORIZZATORE',
 'VELVET CARE SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ',
 'Coventry Incinerator EPR/NP3739PD',
 'ACQUA MINERALE SAN BENEDETTO S.P.A.',
 'Egger Holzwerkstoffe Brilon GmbH & Co. KG',
 'DOW SILICONES BELGIUM',
 'Tammervoima Oy, Tammervoima Oy:n hyötyvoimalaitos',
 'VALORGIS',
 'Glencore Nikkelverk',
 'ILVA SPA STABILIMENTO DI NOVI LIGURE',
 'DONG Olierør A/S, Råolierørledningen og råolieterminalen',
 'Eastcroft EFW Plant',
 'VISCOCEL',
 'CHIMIREC-PPM',
 'AbfallWirtschaftsGesellschaft mbH (AWG)',
 'SATOM Monthey',
 'Horndean B Well Site',
 'Ri.Plastic S.p.A.',
 'BIOFOS  Spildevandscenter  Avedøre A/S',
 'SAIDEF Fribourg',
 'HACER TRAITEMENTS DE SURFACE',
 'AZSA - FÁBRICA DE ZINC ELECTROLÍTICO',
 'Stena Recycling Cools',
 'TERMOVALORIZZATORE DI ACERRA',
 'Østfold Energi, Rakkestadanlegget',
 'PROTIRES',
 'Ticona GmbH',
 'ALIER',
 'IMPIANTO DI DEPURAZIONE ACQUE REFLUE DI RANICA',
 'Centrala Avloppsreningsverket',
 'BOEBLINGEN-SINDELFINGEN I ',
 'GALVASWISS AG Aarberg',
 'Abwasserverband Isar-Loisachgruppe, Kläranlage Wolfratshausen',
 'CANDIANI SPA',
 "EAU D 'AZUR",

In [7]:
lat = 41.041963
lon = -0.556805

df1_filtered = df_pdh_data[
    (df_pdh_data["lat"] == lat) &
    (df_pdh_data["lon"] == lon)
]

df2_filtered = df_icpe[
    (df_icpe["lat"] == lat) &
    (df_icpe["lon"] == lon)
]

display(df1_filtered)
display(df2_filtered)

,category,lat,lon,name,city,country,type,sector,source_type,data_collection_method,...,source_url,dataset_id,dataset_name,pfas_values,unit,pfas_sum,details,matrix,date,year
1286107,Measurement,41.041963,-0.556805,PHYTEUROP INDUSTRY - REJETS STEP PRESLES (Aval),MONTREUIL-BELLAY,France,Sampling location,NaN,Authorities,Public data - Download,...,https://www.pays-de-la-loire.developpement-dur...,142,France - ICPE,"[{""cas_id"": ""375-22-4"", ""unit"": ""ng/l"", ""subst...",ng/l,2500.0,"{""url_fiche"": ""https://www.georisques.gouv.fr/...",Wastewater,2026-02-11,2026.0
1286108,Measurement,41.041963,-0.556805,PHYTEUROP INDUSTRY - REJETS STEP PRESLES (Aval),MONTREUIL-BELLAY,France,Sampling location,NaN,Authorities,Public data - Download,...,https://www.pays-de-la-loire.developpement-dur...,142,France - ICPE,"[{""cas_id"": ""375-95-1"", ""unit"": ""ng/l"", ""subst...",ng/l,2500.0,"{""url_fiche"": ""https://www.georisques.gouv.fr/...",Wastewater,2026-01-22,2026.0
1286109,Measurement,41.041963,-0.556805,PHYTEUROP INDUSTRY - REJETS STEP PRESLES (Aval),MONTREUIL-BELLAY,France,Sampling location,NaN,Authorities,Public data - Download,...,https://www.pays-de-la-loire.developpement-dur...,142,France - ICPE,"[{""cas_id"": ""2706-91-4"", ""unit"": ""ng/l"", ""subs...",ng/l,2500.0,"{""url_fiche"": ""https://www.georisques.gouv.fr/...",Wastewater,2025-12-22,2025.0

,category,lat,lon,name,city,country,type,sector,source_type,data_collection_method,...,source_url,dataset_id,dataset_name,pfas_values,unit,pfas_sum,details,matrix,date,year
0,Measurement,41.041963,-0.556805,PHYTEUROP INDUSTRY - REJETS STEP PRESLES (Aval),MONTREUIL-BELLAY,France,Sampling location,NaN,Authorities,Public data - Download,...,https://www.pays-de-la-loire.developpement-dur...,142,France - ICPE,"[{""cas_id"":""375-22-4"",""unit"":""ng/l"",""substance...",ng/l,2500.0,"{""url_fiche"":""https://www.georisques.gouv.fr/r...",Wastewater,2026-02-11,2026
1,Measurement,41.041963,-0.556805,PHYTEUROP INDUSTRY - REJETS STEP PRESLES (Aval),MONTREUIL-BELLAY,France,Sampling location,NaN,Authorities,Public data - Download,...,https://www.pays-de-la-loire.developpement-dur...,142,France - ICPE,"[{""cas_id"":""375-95-1"",""unit"":""ng/l"",""substance...",ng/l,2500.0,"{""url_fiche"":""https://www.georisques.gouv.fr/r...",Wastewater,2026-01-22,2026
2,Measurement,41.041963,-0.556805,PHYTEUROP INDUSTRY - REJETS STEP PRESLES (Aval),MONTREUIL-BELLAY,France,Sampling location,NaN,Authorities,Public data - Download,...,https://www.pays-de-la-loire.developpement-dur...,142,France - ICPE,"[{""cas_id"":""2706-91-4"",""unit"":""ng/l"",""substanc...",ng/l,2500.0,"{""url_fiche"":""https://www.georisques.gouv.fr/r...",Wastewater,2025-12-22,2025